sonar.projectKey=dishap-22_fastapi-sonarqube-demo
sonar.organization=dishap-22

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

sonar.python.version=3.12